// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCe88S-NcHuk8oM8Msv7GKo_qd-S83BpU',
    appId: '1:736427716625:web:fa95a0a6c10ff03d7081b0',
    messagingSenderId: '736427716625',
    projectId: 'recipe-c716a',
    authDomain: 'recipe-c716a.firebaseapp.com',
    storageBucket: 'recipe-c716a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4KMLJ3_xW8SGNKXx4bJhvLRY_2NqXko',
    appId: '1:736427716625:android:99837daffbbac1347081b0',
    messagingSenderId: '736427716625',
    projectId: 'recipe-c716a',
    storageBucket: 'recipe-c716a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfs0CWXBj5U2i7wBEdD63o7nJ8GZStj1o',
    appId: '1:736427716625:ios:2357159e7eeafb697081b0',
    messagingSenderId: '736427716625',
    projectId: 'recipe-c716a',
    storageBucket: 'recipe-c716a.appspot.com',
    iosClientId: '736427716625-ipoeva51pjbmrj1lg6hq739sf46tvmfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfs0CWXBj5U2i7wBEdD63o7nJ8GZStj1o',
    appId: '1:736427716625:ios:2357159e7eeafb697081b0',
    messagingSenderId: '736427716625',
    projectId: 'recipe-c716a',
    storageBucket: 'recipe-c716a.appspot.com',
    iosClientId: '736427716625-ipoeva51pjbmrj1lg6hq739sf46tvmfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
